spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=master
spring.datasource.password=masterpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.issuer=studenthub

internal.secret: "${INTERNAL_SECRET}"
