spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=master
spring.datasource.password=masterpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=7fef1f5cfaa955a223b60420bf7f95a7
security.jwt.issuer=studenthub
