spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://postgres:5432/auth_db
spring.datasource.username=auth_user
spring.datasource.password=auth_pass

security.jwt.secret=7fef1f5cfaa955a223b60420bf7f95a7
security.jwt.issuer=studenthub
