apiVersion: v1
kind: Secret
metadata:
  name: studenthub-jwt
type: Opaque
stringData:
  secret: {{ .Values.jwt.secret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-secret
type: Opaque
stringData:
  secret: {{ .Values.internal.secret | quote }}
