apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/auth_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "master"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "masterpass"
