apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.auth.containerPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/auth_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "master"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "masterpass"

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect

            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: studenthub-jwt
                  key: secret

            - name: SECURITY_JWT_ISSUER
              value: studenthub

            - name: INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: internal-secret
                  key: secret