apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}-auth
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-auth
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.auth.containerPort }}
