apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-business
spec:
  selector:
    app: {{ .Release.Name }}-business
  ports:
    - port: 80
      targetPort: {{ .Values.business.containerPort }}
