spring.application.name=student_hub

spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=lms
spring.datasource.password=lms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth-service.base-url=${AUTH_SERVICE_URL:http://localhost:8080}