spring.application.name=business-service

spring.datasource.url=jdbc:postgresql://postgres:5432/business_db
spring.datasource.username=master
spring.datasource.password=masterpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth-service.base-url=${AUTH_SERVICE_URL:http://studenthub-auth}
internal.secret: "${INTERNAL_SECRET}"