spring.application.name=student_hub

spring.datasource.url=jdbc:postgresql://localhost:5432/business_db
spring.datasource.username=business_user
spring.datasource.password=business_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

auth-service.base-url=${AUTH_SERVICE_URL:http://localhost:8080}